SRC_DIR := src
BUILD_DIR := build

# Files
# wildcard/patsubst stuff generated by LLM
SRCS := $(wildcard $(SRC_DIR)/*.c)
OBJS := $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))
DEPS := $(wildcard $(SRC_DIR)/*.h)
TARGET := $(BUILD_DIR)/main

# AVR compiler flags
# Currently requires double entry of parameters w/ upload script
MCU := atmega328p
F_CPU := 16000000UL
CFLAGS := -Os -g -DF_CPU=$(F_CPU) -mmcu=$(MCU)
LDFLAGS := -mmcu=$(MCU)

# Rules
all: $(TARGET)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# Compile object files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c $(DEPS)
	avr-gcc $(CFLAGS) -c $< -o $@

# Link executable and generate annotated assembly for my own study
$(TARGET): $(OBJS)
	avr-gcc $(LDFLAGS) -o $@ $^
	avr-objdump -d -S $@ > $(basename $@).lst
	avr-objcopy -O ihex -R .eeprom $(TARGET) $(basename $@).hex

# Clean rule
clean:
	rm -rf $(BUILD_DIR)
